# base image
FROM python:3

# defines a working directory
WORKDIR /usr/app

# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -U flask-cors
COPY . .

# default command: run in development mode
CMD ["flask", "run", "--host=0.0.0.0", "--cert=adhoc"]